name: CI Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  jest:
    name: Jest Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: make install -B

      - name: Run Jest
        run: make jest -B

  eslint:
    name: ESLint Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: make install -B

      - name: Run ESLint
        run: make eslint -B

  prettier:
    name: Prettier Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: make install -B

      - name: Run Prettier
        run: make prettier -B